#
# NTools config.yml v0.0.1
#
enable-debug-messages: false

trench-block-blacklist:
  - bedrock
  - obsidian
  - mob_spawner
  - hopper
  - chest

tray-block-whitelist:
  - dirt
  - netherrack

gui:
  # generic gui to select a type of tool to buy
  generic-buy:
    size: 9
    name: "&6&lBuy Tools"
    1:
      slot: 0
      name: "&b&lMulti Tools"
      material: ghast_tear:0
      lore:
        - "&7 "
        - "&7&oClick this to buy multi tools"
        - "&7 "
      enchantments:
        - lure:10
      open-multi: true
    2:
      slot: 1
      name: "&b&lTrench Tools"
      material: magma_cream:0
      lore:
        - "&7 "
        - "&7&oClick this to buy trench tools"
        - "&7 "
      enchantments:
        - fire_aspect:10
      open-trench: true
    3:
      slot: 2
      name: "&b&lTray Tools"
      material: magma_cream:0
      lore:
        - "&7 "
        - "&7&oClick this to buy tray tools"
        - "&7 "
      enchantments:
        - fire_aspect:10
      open-tray: true

  # multi tool buy gui
  multi-buy:
    size: 9
    name: "&6&lBuy Multi Tools"
    1:
      slot: 0
      tool-id: 1
      price: 3000000
      name: "&a&lForged Pickaxe"
      material: diamond_pickaxe:0
      lore:
        - "&2&l**Forged**"
        - "&7 "
        - "&7Mode: &e&lTRENCH"
        - "&7Radius: &b&l3x3"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$3,000,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    2:
      slot: 7
      name: "&e&lMulti Tool Information"
      material: book:0
      lore:
        - "&7 "
        - "&7&oMulti Tools can be purchase by"
        - "&7&oleft-clicking the respective tool."
        - "&7 "
        - "&6&oMulti tools have special properties,"
        - "&6&owhich means they can be configured to suit"
        - "&6&oyour trench / tray needs."
        - "&7 "
      enchantments:
        - durability:10
    3:
      slot: 8
      name: "&c&lBack"
      material: barrier:0
      lore:
        - "&7 "
        - "&7&oReturn to the previous screen."
        - "&7 "
      back-button: true

  # trench buy gui
  trench-buy:
    size: 9
    name: "&6&lBuy Trench Tools"
    1:
      slot: 0
      tool-id: 1
      price: 800000
      name: "&eTrench Pickaxe &7(&63x3&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Holes I**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$800,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    2:
      slot: 1
      price: 1250000
      name: "&eTrench Pickaxe &7(&65x5&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Holes II**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$1,250,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    3:
      slot: 2
      price: 1750000
      name: "&eTrench Pickaxe &7(&67x7&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Holes III**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$1,750,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    4:
      slot: 7
      name: "&e&lTrench Tool Information"
      material: book:0
      lore:
        - "&7 "
        - "&7&oTrench Tools can be purchase by"
        - "&7&oleft-clicking the respective tool."
        - "&7 "
        - "&6&oTrench Tools will help when excavating"
        - "&6&olarge sections of the world..."
        - "&7 "
      enchantments:
        - durability:10
    5:
      slot: 8
      name: "&c&lBack"
      material: barrier:0
      lore:
        - "&7 "
        - "&7&oReturn to the previous screen."
        - "&7 "
      back-button: true

  # tray buy gui
  tray-buy:
    size: 9
    name: "&6&lBuy Tray Tools"
    1:
      slot: 0
      price: 800000
      name: "&eTray Pickaxe &7(&63x3&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Gutters I**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$800,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    2:
      slot: 1
      price: 1250000
      name: "&eTray Pickaxe &7(&65x5&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Gutters II**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$1,250,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    3:
      slot: 2
      price: 1750000
      name: "&eTray Pickaxe &7(&67x7&7)"
      material: diamond_pickaxe:0
      lore:
        - "&6&l**Gutters III**"
        - "&7 "
        - "&a&oThis pickaxe was forged in an unknown place,"
        - "&a&oits potential is still be realised. Use,"
        - "&a&oabuse and reap the rewards of this tool."
        - "&7 "
        - "&cPrice: &l-$1,750,000"
      enchantments:
        - dig_speed:5
        - durability:10
      purchasable: true
    4:
      slot: 7
      name: "&e&lTray Tool Information"
      material: book:0
      lore:
        - "&7 "
        - "&7&oTray Tools can be purchase by"
        - "&7&oleft-clicking the respective tool."
        - "&7 "
        - "&6&oTray Tools will aid the removal of blocks"
        - "&6&olike dirt and netherrack from your trays..."
        - "&7 "
      enchantments:
        - durability:10
    5:
      slot: 8
      name: "&c&lBack"
      material: barrier:0
      lore:
        - "&7 "
        - "&7&oReturn to the previous screen."
        - "&7 "
      back-button: true

  # multi tool options gui (opened by shift right clicking with the tool)
  multi-tool-options:
    size: 18
    name: "&6&lMulti Tool Options"
    1:
      slot: 5
      name: "&b&lMode Switch"
      material: ender_pearl:0
      lore:
        - "&7 "
        - "&7&oClick this to change your tools"
        - "&7&omode. There are tray and trench modes."
        - "&7 "
      switch-mode-when-clicked: true
    2:
      slot: 3
      name: "&a&l+Radius"
      material: stained_glass_pane:5
      lore:
        - "&7 "
        - "&7&oClick to increase your tools"
        - "&7&obreak radius by 1 block."
        - "&7 "
      increase-radius-when-clicked: true
    3:
      slot: 2
      name: "&c&l-Radius"
      material: stained_glass_pane:14
      lore:
        - "&7 "
        - "&7&oClick to decrease your tools"
        - "&7&obreak radius by 1 block."
        - "&7 "
      decrease-radius-when-clicked: true
    4:
      slot: 13
      name: "&e&lMulti Tool Information"
      material: book:0
      lore:
        - "&7 "
        - "&7&oMulti tools have special properties,"
        - "&7&owhich means they can be configured to suit"
        - "&7&oyour trench / tray needs. Click the buttons"
        - "&7&oin this gui to configure your tool."
        - "&7 "
        - "&6&oYou must be holding your multi tool."
        - "&7 "
      enchantments:
        - durability:10