name: ToolsPlus
version: 0.3.8
main: dev.nuer.tp.ToolsPlus
author: Nuer
description: A custom tools plugin
api-version: 1.13
commands:
  nt:
    usage: /<command>
    description: Base command for ToolsPlus. See GitHub wiki for command help
    aliases: [tools, tool, toolsplus]