name: ToolsPlus
version: 0.3.6
main: dev.nuer.nt.ToolsPlus
author: Nuer
description: A custom tools plugin
api-version: 1.13
commands:
  tools:
    usage: /<command>
    description: Base command for ToolsPlus. See GitHub wiki for command help
  nt:
    usage: /<command>
    description: Base command for ToolsPlus. See GitHub wiki for command help