name: ToolsPlus
version: 1.5.0.1
main: dev.nuer.tp.ToolsPlus
author: Nuer
description: A custom tools plugin
api-version: 1.13
commands:
  t+:
    usage: /<command>
    description: Base command for Tools+, please see the GitHub wiki pages for command & permission help.
    aliases: [nt, tool, tool+, tools, tools+, toolsplus]