name: NTools
version: 0.2.8
main: dev.nuer.nt.NTools
author: Nuer
description: A custom tools plugin
api-version: 1.13
commands:
  tools:
    usage: /<command>
    description: Base command for NTools. See GitHub wiki for command help
  nt:
    usage: /<command>
    description: Base command for NTools. See GitHub wiki for command help